name: Main

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

jobs:
  build-and-deploy:
    name: Build & Deploy to MSquared Platform
    runs-on: ubuntu-latest
    environment: production-deployment

    env:
      MSQUARED_API_KEY: '${{ secrets.MSQUARED_API_KEY }}'
      MSQUARED_PROJECT_ID: '${{ secrets.MSQUARED_PROJECT_ID }}'
      MSQUARED_WORLD_ID: '${{ secrets.MSQUARED_WORLD_ID }}'
      MSQUARED_BUCKET_ID: '${{ secrets.MSQUARED_BUCKET_ID }}'

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build
      - run: npm run deploy
